site_name: Watchdog Docs
site_url: https://docs.abls-habitat.fr/
repo_url: https://svn.abls-habitat.fr/repo/Watchdog/prod/
repo_name: Watchdog Repository
site_description: Documentation du projet domotique Watchdog
site_author: Sébastien et Bruno Lefèvre
site_dir: docs_builded
extra_css: [extra.css]

nav:
 - Présentation : presentation.md
 - Guide de démarrage: guide_demarrage.md
 - Utilisateurs: users.md
 - Programmation D.L.S: dls.md
 - Inventaire des Visuels: visuels.md
 - Auteurs: auteurs.md

theme:
 name: readthedocs
 locale: fr
