<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Config_model extends CI_Model
 { public function __construct()
    { parent::__construct(); }


/******************************************************************************************************************************/
    function get_instances()
     { $this->db->select("DISTINCT(instance_id)");
   		  $this->db->from('config');
       return $this->db->get()->result();
     }
/******************************************************************************************************************************/
    function get_list($host,$thread)
     { $this->db->select("*");
   		  $this->db->from('config');
       if(isset($host)) $this->db->where('instance_id=',$host);
       if(isset($thread)) $this->db->where('nom_thread=',$thread);
       return $this->db->get()->result();
     }
/******************************************************************************************************************************/
    function get_param($host,$thread,$param)
     { $this->db->select("*");
   		  $this->db->from('config');
       if(isset($host)) $this->db->where('instance_id=',$host);
       if(isset($thread)) $this->db->where('nom_thread=',$thread);
       if(isset($param)) $this->db->where('nom=',$param);
       $result = $this->db->get()->row();
       if (null !== $result) return $result->valeur;
       else return("Unknown");
     }
/******************************************************************************************************************************/
    function set($host,$thread,$param,$valeur)
     { $this->db->set('instance_id', $host);
       $this->db->set('nom_thread', $thread);
       $this->db->set('nom', $param);
       $this->db->set('valeur', $valeur);
   		  return($this->db->replace('config'));
     }
/******************************************************************************************************************************/
    function del($host,$thread,$param,$valeur)
     { $this->db->where('instance_id', $host);
       $this->db->where('nom_thread', $thread);
       $this->db->where('nom', $param);
   		  return($this->db->delete('config'));
     }
}
/*----------------------------------------------------------------------------------------------------------------------------*/
