<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Icons_model extends CI_Model
 { public function __construct()
    { parent::__construct(); }

/******************************************************************************************************************************/
 function class_get($id=NULL)
  { $this->db->select("*");
		  $this->db->from('class');
    $this->db->where('id=',$id);
    return $this->db->get()->row();
  }
/******************************************************************************************************************************/
 function class_list()
  { $this->db->select("*");
		  $this->db->from('class');
		  $this->db->order_by('libelle');
    return $this->db->get()->result();
  }

/******************************************************************************************************************************/
 function class_count()
  { $this->db->from('class');
    return $this->db->count_all_results();
  }
    
/******************************************************************************************************************************/
 function class_create($params)
  { $this->db->insert('class',$params);
     return $this->db->insert_id();
  }
/******************************************************************************************************************************/
 function class_update($id,$params)
  { $this->db->where('id',$id);
    return $this->db->update('class',$params);
  }
/******************************************************************************************************************************/    
 function class_delete($id)
  { return $this->db->delete('class',array('id'=>$id)); }

/******************************************************************************************************************************/
 function icon_get($id=NULL)
  { $this->db->select("*");
		  $this->db->from('icons');
    $this->db->where('id=',$id);
    return $this->db->get()->row();
  }
/******************************************************************************************************************************/
 function icons_list($id=NULL)
  { $this->db->select("*");
		  $this->db->from('icons');
    $this->db->where('id_classe=',$id);
		  $this->db->order_by('libelle');
    return $this->db->get()->result();
  }
/******************************************************************************************************************************/
 function icons_count()
  { $this->db->from('icons');
    return $this->db->count_all_results();
  }
    
/******************************************************************************************************************************/
 function icon_add($params)
  { $this->db->insert('icons',$params);
     return $this->db->insert_id();
  }
/******************************************************************************************************************************/
 function icon_update($id,$params)
  { $this->db->where('id',$id);
    return $this->db->update('icons',$params);
  }
/******************************************************************************************************************************/    
 function icon_delete($id)
  { return $this->db->delete('icons',array('id'=>$id)); }
}
/*----------------------------------------------------------------------------------------------------------------------------*/
