<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Dls_model extends CI_Model
 { public function __construct()
    { parent::__construct(); }
    

/******************************************************************************************************************************/
    function get($id)
     { $this->db->select("d.id, d.tech_id, syn.access_level, d.package, d.name, d.shortname, d.actif,".
                         " d.compil_date, d.compil_status, d.nbr_compil, d.nbr_ligne, d.sourcecode,".
                         "parent_syn.page as ppage, syn.page as page");
   		  $this->db->from('dls as d');
		     $this->db->join('syns as syn','d.syn_id=syn.id');
		     $this->db->join('syns as parent_syn','syn.parent_id=parent_syn.id');
   		  $this->db->where('d.id=',$id);
       return $this->db->get()->row();
     }
/******************************************************************************************************************************/
    function get_error_log($id)
     { $this->db->select("errorlog");
   		  $this->db->where('id=',$id);
       return $this->db->get_where('dls')->row()->errorlog;
     }
    
 
    /*
     * Get all dlss count
     */
    function get_all_dls_count()
    {
        $this->db->from('dls');
        return $this->db->count_all_results();
    }
    
	
/******************************************************************************************************************************/
	public function get_count()
	 {	/*$this->db->where('s.access_level<=', $access_level);
		  $this->db->join('syns as s','d.syn_id=s.id');*/
		  $query = $this->db->select("COUNT(*) as num")->get("dls d");
		  $result = $query->row();
		  if(isset($result)) return $result->num;
		  return 0;
	 }
	
/******************************************************************************************************************************/
 function get_all()
  { $this->db->select("d.id, d.tech_id, syn.access_level, d.package, d.name, d.shortname, d.actif, d.compil_date, d.compil_status, d.nbr_compil, d.nbr_ligne, parent_syn.page as ppage, syn.page as page");
		  $this->db->order_by('ppage', 'desc');
		  $this->db->order_by('page', 'desc');
		  $this->db->order_by('shortname', 'desc');
		  /*$this->db->where('syn.access_level<=', $this->session->user_access_level);*/
		  $this->db->from('dls as d');
		  $this->db->join('syns as syn','d.syn_id=syn.id');
		  $this->db->join('syns as parent_syn','syn.parent_id=parent_syn.id');
    $result = $this->db->get()->result();
    error_log ( 'get_all_dls '. $this->db->last_query() );
    return $result;
  }
	
/******************************************************************************************************************************/
 function add($params)
  { $this->db->insert('dls',$params);
     return $this->db->insert_id();
  }
/******************************************************************************************************************************/
 function update($id,$params)
  { $this->db->where('id',$id);
    return $this->db->update('dls',$params);
  }
/******************************************************************************************************************************/    
 function delete($id)
  { return $this->db->delete('dls',array('id'=>$id)); }
/******************************************************************************************************************************/    
 function activate($id)
  { $this->db->where('id',$id);
    return $this->db->update('dls', array('actif'=>'1'));
  }
/******************************************************************************************************************************/    
 function deactivate($id)
  { $this->db->where('id',$id);
    return $this->db->update('dls', array('actif'=>'0'));
  }
}
/*----------------------------------------------------------------------------------------------------------------------------*/
