<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Syn_model extends CI_Model
 { public function __construct()
    { parent::__construct(); }
    
/******************************************************************************************************************************/
    function get($id)
	    { $this->db->select("syn.id,syn.libelle,syn.page,syn.access_level,parent.id as pid,parent.page as ppage ");
       $this->db->from("syns as syn");
       $this->db->join("syns as parent", "syn.parent_id=parent.id", "INNER" );
       /*$this->db->where("syn.access_level<=", $this->session->user_access_level );*/
       $this->db->where("syn.id=", $id );
       return $this->db->get()->row();
     }
    
    /*
     * Get all syns count
     */
    function get_all_syns_count()
     { $this->db->from('syns');
       return $this->db->count_all_results();
     }
	
/******************************************************************************************************************************/
	   public function get_count()
	    { /*$this->db->where("syn.access_level<=", $this->session->user_access_level );*/
       $this->db->from("syns as syn");
		     $query = $this->db->select("COUNT(*) as num")->get();
		     $result = $query->row();
		     if(isset($result)) return $result->num;
		     return 0;
	    }
        
/******************************************************************************************************************************/
    function get_all()
     { $this->db->select("syn.id,syn.libelle,syn.page,syn.access_level,parent.id as pid,parent.page as ppage ");
       $this->db->from("syns as syn");
       $this->db->join("syns as parent", "syn.parent_id=parent.id", "INNER" );
       /*$this->db->where("syn.access_level<=", $this->session->user_access_level );*/
       $result = $this->db->get()->result();
       error_log ( 'get_all_syns '. $this->db->last_query() );
       return $result;
     }
	
/******************************************************************************************************************************/
    function create($params)
     { $this->db->insert('syns',$params);
       return $this->db->insert_id();
     }
    
/******************************************************************************************************************************/
    function update($id,$params)
     { $this->db->where('id',$id);
       return $this->db->update('syns',$params);
     }
    
/******************************************************************************************************************************/
    function delete($id)
     { $this->db->where('access_level<=', $this->session->user_access_level);
       return $this->db->delete('syns',array('id'=>$id));
     }
  }
