<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Horloges_model extends CI_Model
 { public function __construct()
    { parent::__construct(); }


/******************************************************************************************************************************/
    function get($tech_id)
     { $this->db->select("d.id, d.tech_id, syn.access_level, d.package, d.name, d.shortname, d.actif,".
                         " d.compil_date, d.compil_status, d.nbr_compil, d.nbr_ligne, d.sourcecode,".
                         "parent_syn.page as ppage, syn.page as page");
   		  $this->db->from('dls as d');
		     $this->db->join('syns as syn','d.syn_id=syn.id');
		     $this->db->join('syns as parent_syn','syn.parent_id=parent_syn.id');
   		  $this->db->where('d.tech_id=',$tech_id);
       return $this->db->get()->row();
     }
/******************************************************************************************************************************/
    function get_error_log($tech_id)
     { $this->db->select("errorlog");
   		  $this->db->where('tech_id=',$tech_id);
       return $this->db->get_where('dls')->row()->errorlog;
     }
/******************************************************************************************************************************/
	public function get_total_dls()
	 {	$this->db->where('s.access_level<=', $this->session->user_access_level);
		  $this->db->join('syns as s','d.syn_id=s.id');
		  $query = $this->db->select("COUNT(*) as num")->get("dls d");
		  $result = $query->row();
		  if(isset($result)) return $result->num;
		  return 0;
	 }
 public function get_nbr_lignes()
  {	$this->db->select( 'SUM(nbr_ligne) AS nbr_lignes' );
	   $response = $this->db->get('dls');
 	 	return $response->row()->nbr_lignes;
  }
/******************************************************************************************************************************/
 function get_all_dls($start, $length)
  { $this->db->select("d.id, d.tech_id, syn.access_level, d.package, d.name, d.shortname, d.actif, d.compil_date, d.compil_status, d.nbr_compil, d.nbr_ligne, parent_syn.page as ppage, syn.page as page");
		  $this->db->order_by('ppage', 'desc');
		  $this->db->order_by('page', 'desc');
		  $this->db->order_by('shortname', 'desc');
		  $this->db->where('syn.access_level<=', $this->session->user_access_level);
		  $this->db->from('dls as d');
		  $this->db->join('syns as syn','d.syn_id=syn.id');
		  $this->db->join('syns as parent_syn','syn.parent_id=parent_syn.id');
    if ($length != 0) { $this->db->limit($length,$start); }
    $result = $this->db->get();
    error_log ( 'get_all_dls '. $this->db->last_query() );
    return $result;
  }

/******************************************************************************************************************************/
 function add($params)
  { $this->db->insert('dls',$params);
     return $this->db->insert_id();
  }
/******************************************************************************************************************************/
 function update($tech_id,$params)
  { $this->db->where('tech_id',$tech_id);
    return $this->db->update('dls',$params);
  }
/******************************************************************************************************************************/
 function delete($tech_id)
  { return $this->db->delete('dls',array('tech_id'=>$id)); }
/******************************************************************************************************************************/
 function start($tech_id)
  { $this->db->where('tech_id',$tech_id);
    return $this->db->update('dls', array('actif'=>'1'));
  }
/******************************************************************************************************************************/
 function stop($tech_id)
  { $this->db->where('tech_id',$tech_id);
    return $this->db->update('dls', array('actif'=>'0'));
  }
}
/*----------------------------------------------------------------------------------------------------------------------------*/
